// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/gin-gonic/gin"
	"go-job/node/api"
	"go-job/node/router"
	"go-job/node/service"
)

// Injectors from wire.go:

func InitWebServer() *WebContainer {
	iJobService := service.NewJobService()
	jobApi := api.NewJobApi(iJobService)
	iNodeService := service.NewNodeService()
	nodeApi := api.NewNodeApi(iNodeService)
	engine := router.NewWebRouter(jobApi, nodeApi)
	webContainer := &WebContainer{
		Engine: engine,
		JobSvc: iJobService,
	}
	return webContainer
}

// wire.go:

type WebContainer struct {
	Engine *gin.Engine
	JobSvc service.IJobService
}
