server:
  name: "master"
  ip: "0.0.0.0"
  port: 8080
  key: "k6CswdUm77WKcbM68UQUuxVsHSpTCwgK"

data:
  upload_job_dir: "./data/upload_job"

mysql:
  username: root
  password: 123456
  host: 127.0.0.1
  port: 3306
  database: "go-job"
  max_idle_conn: 2
  max_open_conn: 5
  show_sql: true

redis:
  auth: "123456"
  addr: "127.0.0.1:6379"
  db: 0
  
smtp:
  qq:
    sender: "xxx@qq.com"
    key: xxx
    smtp_host: "xx"
    smtp_port: 0
  netease163:
    sender: "xxx@163.com"
    key: xxx
    smtp_host: "xx"
    smtp_port: 0


metrics:
  node:
    interval: 10
    timeout: 2


oauth2:
  github:
    client_id: xx
    client_secret: xx
    redirect_url: xx