// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/gin-gonic/gin"
	"go-job/internal/pkg/email"
	"go-job/master/api"
	"go-job/master/database"
	"go-job/master/pkg/middleware"
	"go-job/master/pkg/notify"
	"go-job/master/repo"
	"go-job/master/repo/cache"
	"go-job/master/router"
	"go-job/master/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitWebServer() *WebContainer {
	v := middleware.NewGinMiddlewares()
	db := database.NewMySQLWithGORM()
	iJobRepo := repo.NewJobRepo(db)
	iNodeRepo := repo.NewNodeRepo(db)
	iUserRepo := repo.NewUserRepo(db)
	iEmailService := email.InitEmailService()
	iNotifyStore := notify.InitMemoryNotifyStore(iEmailService)
	iJobService := service.NewJobService(iJobRepo, iNodeRepo, iUserRepo, iNotifyStore)
	iUserService := service.NewUserService(iUserRepo)
	jobApi := api.NewJobApi(iJobService, iUserService)
	iJobRecordRepo := repo.NewJobRecordRepo(db)
	iJobRecordService := service.NewJobRecordService(iJobRecordRepo, iNotifyStore)
	jobRecordApi := api.NewJobRecordApi(iJobRecordService)
	iNodeService := service.NewNodeService(iNodeRepo, iJobRepo)
	nodeApi := api.NewNodeApi(iNodeService)
	cmdable := database.NewRedisClient()
	iEmailCodeCache := cache.NewEmailCodeCache(cmdable)
	iEmailCodeRepo := repo.NewEmailCodeRepo(iEmailCodeCache)
	iEmailCodeService := service.NewEmailCodeService(iEmailService, iEmailCodeRepo)
	userApi := api.NewUserApi(iUserService, iEmailCodeService)
	iDashboardService := service.NewDashboardService(iJobRepo, iJobRecordRepo)
	dashboardApi := api.NewDashboardApi(iDashboardService)
	engine := router.NewWebRouter(v, jobApi, jobRecordApi, nodeApi, userApi, dashboardApi)
	webContainer := &WebContainer{
		Engine:      engine,
		MysqlDB:     db,
		JobSvc:      iJobService,
		NotifyStore: iNotifyStore,
	}
	return webContainer
}

// wire.go:

type WebContainer struct {
	Engine      *gin.Engine
	MysqlDB     *gorm.DB
	JobSvc      service.IJobService
	NotifyStore notify.INotifyStore
}
