// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/gin-gonic/gin"
	"go-job/master/api"
	"go-job/master/database"
	"go-job/master/pkg/middleware"
	"go-job/master/repo"
	"go-job/master/router"
	"go-job/master/service"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	v := middleware.NewGinMiddlewares()
	db := database.NewMySQLWithGORM()
	iJobRepo := repo.NewJobRepo(db)
	iJobService := service.NewJobService(iJobRepo)
	jobApi := api.NewJobApi(iJobService)
	engine := router.NewWebRouter(v, jobApi)
	return engine
}
